# Main website config
# All global variables are stored here
title: Iurii /Yuriy/ Krasnoshchok
description: >- # this means to ignore newlines until "baseurl:"
  Iurii Krasnoshchok — Software Engineer, IT Consultant, DevOps, DBA, Solution Architect, CTO.
keywords: >
  iurii,yuriy,yurii,krasnoshchok,krasnoschok,software,programming,IT,engineering,development,DevOps,DBA

url: "https://iurii.net"
baseurl: "" # the subpath of your site, e.g. /blog
email: hello@iurii.net
location: "CET"
twitter: https://twitter.com/iurii_k
github: https://github.com/aka-rider/
linkedin: https://linkedin.com/in/iuriik/
medium: https://medium.com/@aka.rider

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .*
  - gemfiles/
  - Gemfile.lock
  - Gemfile
  - Makefile
